
name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['^8.3']
        laravel: ['^11.0']
        exclude:
          - php: '8.3'
            laravel: '^11.0'

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: php-^8.3-laravel-^11.9-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, pdo_sqlite, tokenizer, xml
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:^11.9" --no-interaction --no-update
          composer update --no-interaction --prefer-dist --no-progress
      - name: Run test suite
        run: composer run-script test
